/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MTSearchApi_constants.h"



const MTSearchApiConstants g_MTSearchApi_constants;

MTSearchApiConstants::MTSearchApiConstants() {
}



