/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MTSearchApi_CONSTANTS_H
#define MTSearchApi_CONSTANTS_H

#include "MTSearchApi_types.h"



class MTSearchApiConstants {
 public:
  MTSearchApiConstants();

};

extern const MTSearchApiConstants g_MTSearchApi_constants;



#endif
