/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MTSearch.h"
#include "MTSearch.tcc"




MTSearch_MTSearchDeal_args::~MTSearch_MTSearchDeal_args() throw() {
}


MTSearch_MTSearchDeal_pargs::~MTSearch_MTSearchDeal_pargs() throw() {
}


MTSearch_MTSearchDeal_result::~MTSearch_MTSearchDeal_result() throw() {
}


MTSearch_MTSearchDeal_presult::~MTSearch_MTSearchDeal_presult() throw() {
}


MTSearch_MTSearchPoi_args::~MTSearch_MTSearchPoi_args() throw() {
}


MTSearch_MTSearchPoi_pargs::~MTSearch_MTSearchPoi_pargs() throw() {
}


MTSearch_MTSearchPoi_result::~MTSearch_MTSearchPoi_result() throw() {
}


MTSearch_MTSearchPoi_presult::~MTSearch_MTSearchPoi_presult() throw() {
}


MTSearch_MTMultiSearch_args::~MTSearch_MTMultiSearch_args() throw() {
}


MTSearch_MTMultiSearch_pargs::~MTSearch_MTMultiSearch_pargs() throw() {
}


MTSearch_MTMultiSearch_result::~MTSearch_MTMultiSearch_result() throw() {
}


MTSearch_MTMultiSearch_presult::~MTSearch_MTMultiSearch_presult() throw() {
}


MTSearch_AttributeFilter_args::~MTSearch_AttributeFilter_args() throw() {
}


MTSearch_AttributeFilter_pargs::~MTSearch_AttributeFilter_pargs() throw() {
}


MTSearch_AttributeFilter_result::~MTSearch_AttributeFilter_result() throw() {
}


MTSearch_AttributeFilter_presult::~MTSearch_AttributeFilter_presult() throw() {
}



